# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    authToken: sample-auth-token

server:
  port: 8081

elasticsearch:
  index:
    name: dev_portal_records
  serverUrl: http://localhost:9200
  apiKey: sample-api-key

logging:
  level:
    au.org.aodn.esindexer: DEBUG
