spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Australia/Hobart

server:
  port: 8080
  error:
    include-stacktrace: never
app:
  http:
    auth-token-header-name: X-API-Key

elasticsearch:
  index:
    name: portal_records

geonetwork:
  host: http://localhost:8080
  records:
    endpoint: ${geonetwork.host}/geonetwork/srv/api/records/{uuid}
  search:
    api:
      endpoint: ${geonetwork.host}/geonetwork/srv/api/search/records/_search

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    au.org.aodn.esindexer: debug