# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    authToken: sample-auth-token

server:
  port: 8081

elasticsearch:
  index:
    name: sample-portal-records
  serverUrl: http://localhost:9200
  apiKey: sample-api-key

geonetwork:
  host:  http://localhost:8080/geonetwork

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
