# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    authToken: Q*z6OfL^4u^1nMhH

server:
  port: 8081

elasticsearch:
  index:
    name: viet_playground
  serverUrl: http://3.27.147.190:9200
  apiKey: NC1Dc19Jb0JsbTJqVmhzNy1OS1k6LTdqN0Y0QktRVHVKRHVpYU1TNkhSZw==

geonetwork:
  host: http://ec2-3-24-110-244.ap-southeast-2.compute.amazonaws.com:8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE