# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    auth-token: Q*z6OfL^4u^1nMhH

server:
  port: 8081

elasticsearch:
  index:
    name: dummy_index
  serverUrl: http://localhost:9201
  apiKey: cU81dHpvb0JkZHZ5YkVCWFNRWjM6ZkR0cVZjN0ZSLUtTZkNZNklXU1JZdw==

geonetwork:
  records:
    endpoint: http://localhost:8080/geonetwork/srv/api/records/
  search:
    api:
      endpoint: http://localhost:8080/geonetwork/srv/api/search/records/_search

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    au.org.aodn.esindexer.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
