spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Australia/Hobart

server:
  port: 8080
  error:
    include-stacktrace: never

# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    auth-token-header-name: X-API-Key
    authToken: ${INDEXER_APIKEY:sample-auth-token}

management:
  endpoints:
    web:
      base-path: /manage
  health:
    elasticsearch:
      enabled: false
  endpoint:
    logfile:
      external-file: /tmp/logs/indexer.log

elasticsearch:
  index:
    name: portal_records

geonetwork:
  host: http://localhost:8080
  search:
    api:
      index: "records"
      endpoint: /geonetwork/srv/api/search

ogc-api:
  host: http://localhost:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    au.org.aodn.esindexer: INFO
