server:
  port: 8081

app:
  geometry:
    enableGridSpatialExtents: true
    reducerPrecision: 4.0

elasticsearch:
  index:
    name: dev_portal_records
  serverUrl: https://dev-discovery-index.es.ap-southeast-2.aws.found.io
  apiKey: sample-api-key

geonetwork:
  host: https://geonetwork.edge.aodn.org.au
  search:
    api:
      index: "records"
      endpoint: /geonetwork/srv/api/search

dataaccess:
  apiKey: temp

datadiscoveryai:
  host: https://data-discovery-ai-edge.aodn.org.au
  baseUrl: /api/v1/ml/process_record
  apiKey: datadiscoveryai-sample-api-key
  internalKey: datadiscoveryai-internal-sample-key

logging:
  level:
    au.org.aodn.indexer: DEBUG
    au.org.aodn.ardcvocabs: INFO
    au.org.aodn.esindexer.utils: INFO
    au.org.aodn.datadiscoveryai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,logfile"
