spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Australia/Hobart

server:
  port: 8080
  error:
    include-stacktrace: never

# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    auth-token-header-name: X-API-Key
    authToken: ${INDEXER_APIKEY:sample-auth-token}

management:
  health:
    elasticsearch:
      enabled: false

elasticsearch:
  index:
    name: portal_records

geonetwork:
  host: http://localhost:8080
  search:
    api:
      index: "records"
      endpoint: /geonetwork/srv/api/search

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    au.org.aodn.esindexer: debug
