# Show only on edge because we do not have a tag version
spring:
  info:
    git:
      location: "classpath:git.properties"

app:
  geometry:
    enableGridSpatialExtents: true
    reducerPrecision: 4.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,logfile"

logging:
  level:
    au.org.aodn.ardcvocabs: DEBUG
