spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Australia/Hobart

server:
  port: 8080
  error:
    include-stacktrace: never

# Client calling the Indexer API must provide this token in the Authorization header
app:
  http:
    auth-token-header-name: X-API-Key
    authToken: ${INDEXER_APIKEY:sample-auth-token}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "health,info"
  health:
    elasticsearch:
      enabled: false
  endpoint:
    logfile:
      external-file: /tmp/logs/indexer.log

elasticsearch:
  index:
    name: portal_records
    categories:
      name: discovery_category

geonetwork:
  host: http://localhost:8080
  search:
    api:
      index: "records"
      endpoint: /geonetwork/srv/api/search

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

# Actuator info point
info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

logging:
  level:
    au.org.aodn.esindexer: INFO
