server:
  port: 8081

elasticsearch:
  index:
    name: dev_portal_records
  serverUrl: https://dev-discovery-index.es.ap-southeast-2.aws.found.io
  apiKey: sample-api-key

geonetwork:
  host: https://geonetwork-edge.aodn.org.au
  search:
    api:
      index: "records"
      endpoint: /geonetwork/srv/api/search

logging:
  level:
    au.org.aodn.indexer: DEBUG
    au.org.aodn.ardcvocabs: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,beans,logfile"
