name: Run Pre-commit Checks

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0

      - name: Configure AWS Credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Get CodeArtifact Auth Token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
          --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
          --domain-owner ${{ steps.aws_auth.outputs.aws-account-id }} \
          --region ${{ vars.AWS_REGION }} \
          --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Get CodeARtifact Maven endpoint
        run: |
          URL=$(aws codeartifact get-repository-endpoint \
          --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
          --repository ${{ vars.CODEARTIFACT_REPO }} \
          --format maven \
          --region ${{ vars.AWS_REGION }} \
          --query repositoryEndpoint --output text)
          echo "CODEARTIFACT_REPO_URL=$URL" >> $GITHUB_ENV


      - name: Set up JDK 17 & maven server
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: 'codeartifact'
          server-username: 'aws'
          server-password: ${{ env.CODEARTIFACT_AUTH_TOKEN }}

      - name: Build with Maven & Publish to CodeArtifact
        run: mvn -B clean deploy --file pom.xml
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
          CODEARTIFACT_REPO_URL: ${{ env.CODEARTIFACT_REPO_URL }}
